const canvas=document.getElementById('builder'),ctx=canvas.getContext('2d');
const flightCanvas=document.getElementById('flightCanvas'),fctx=flightCanvas.getContext('2d');
const parts={
 tank:{name:'FUEL TANK',mass:.55,fuel:4.0,thrust:0,w:72,h:112,icon:'▥',color:'#4f7088',cat:'fuel',top:true,bottom:true},
 tankSmall:{name:'SMALL TANK',mass:.28,fuel:2.0,thrust:0,w:58,h:76,icon:'▤',color:'#55758a',cat:'fuel',top:true,bottom:true},
 engine:{name:'LIQUID ENGINE',mass:.75,fuel:0,thrust:180,w:64,h:58,icon:'◢',color:'#a36d48',cat:'engines',top:true,bottom:true},
 engineVac:{name:'VACUUM ENGINE',mass:.62,fuel:0,thrust:155,w:58,h:72,icon:'▽',color:'#b47b4c',cat:'engines',top:true,bottom:true},
 decoupler:{name:'DECOUPLER',mass:.12,fuel:0,thrust:0,w:76,h:18,icon:'═',color:'#8d8d69',cat:'structure',top:true,bottom:true,decoupler:true},
 adapter:{name:'STACK ADAPTER',mass:.18,fuel:0,thrust:0,w:70,h:28,icon:'◇',color:'#6e7d90',cat:'structure',top:true,bottom:true},
 capsule:{name:'COMMAND CAPSULE',mass:1.1,fuel:0,thrust:0,w:66,h:70,icon:'⌂',color:'#d3a65d',cat:'payload',top:true,bottom:true,capsule:true},
 nose:{name:'NOSE CONE',mass:.12,fuel:0,thrust:0,w:62,h:38,icon:'△',color:'#8594a5',cat:'payload',top:true,bottom:false}
};
let state={parts:[],selected:null,tool:null,zoom:1,pan:{x:0,y:0},grid:true,nodes:true,tab:'fuel',drag:null,stageCount:0};
const $=id=>document.getElementById(id); const uid=()=>Math.random().toString(36).slice(2)+Date.now().toString(36);
const tabs=[...document.querySelectorAll('.tab')]; tabs.forEach(t=>t.onclick=()=>{tabs.forEach(x=>x.classList.remove('active'));t.classList.add('active');state.tab=t.dataset.tab;renderParts()});
function resize(){const r=canvas.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);draw()}; addEventListener('resize',resize);
function renderParts(){const list=$('partsList');list.innerHTML='';Object.entries(parts).filter(([k,p])=>p.cat===state.tab).forEach(([id,p])=>{const e=document.createElement('div');e.className='part-card';e.innerHTML=`<div class="part-icon">${p.icon}</div><div><div class="part-name">${p.name}</div><div class="part-meta">${p.mass.toFixed(2)} t · ${p.fuel? p.fuel.toFixed(1)+' t propellant':p.thrust?p.thrust+' kN':''}</div></div>`;e.onclick=()=>{state.tool=id;state.status='PLACEMENT';$('status').textContent=' '+state.status;};list.appendChild(e)})}
function worldToScreen(x,y){return{x:canvas.clientWidth/2+state.pan.x+x*state.zoom,y:canvas.clientHeight*.82+state.pan.y-y*state.zoom}}
function screenToWorld(x,y){return{x:(x-canvas.clientWidth/2-state.pan.x)/state.zoom,y:-(y-canvas.clientHeight*.82-state.pan.y)/state.zoom}}
function geom(o){const p=parts[o.type];return {x:o.x,y:o.y,w:p.w,h:p.h}}
function node(o,side){const p=parts[o.type];return{x:o.x,y:o.y+(side==='top'?p.h/2:-p.h/2)}}
function snapPosition(o,x,y){let best=null,bd=22/state.zoom;for(const q of state.parts){if(q.id===o.id)continue;for(const a of ['top','bottom'])for(const b of ['top','bottom']){const n=node(q,a),d=Math.hypot(n.x-x,n.y-y);if(d<bd){best={x:n.x,y:n.y+(b==='top'?-parts[o.type].h/2:parts[o.type].h/2),q};bd=d}}}return best||{x,y,q:null}}
function addPart(type,x,y,rot=0,stage=0){const p=parts[type],o={id:uid(),type,x,y,rot,stage};state.parts.push(o);state.selected=o.id;return o}
function placeTool(x,y,mirror=false){if(!state.tool)return;const p=parts[state.tool];let s=snapPosition({type:state.tool},x,y);const o=addPart(state.tool,s.x,s.y,0,0);if(mirror){const m=addPart(state.tool,-s.x,s.y,0,0);m.symmetry=true;o.symmetry=true}state.tool=null;recalc()}
function hit(x,y){for(let i=state.parts.length-1;i>=0;i--){const o=state.parts[i],p=parts[o.type];if(Math.abs(x-o.x)<p.w/2+6/state.zoom&&Math.abs(y-o.y)<p.h/2+6/state.zoom)return o}return null}
function canvasPos(ev){const r=canvas.getBoundingClientRect();return{x:ev.clientX-r.left,y:ev.clientY-r.top}}
canvas.addEventListener('mousedown',e=>{const s=canvasPos(e),w=screenToWorld(s.x,s.y);if(e.button===1||e.buttons===4){state.drag={pan:true,x:s.x,y:s.y,px:state.pan.x,py:state.pan.y};return}if(e.button===2){const o=hit(w.x,w.y);if(o){o.rot=(o.rot+90)%360;recalc()}return}if(state.tool){placeTool(w.x,w.y,e.shiftKey);return}const o=hit(w.x,w.y);state.selected=o?.id||null;if(o){state.drag={part:o,x0:w.x,y0:w.y,ox:o.x,oy:o.y};}updateInspector();draw()});
canvas.addEventListener('mousemove',e=>{if(!state.drag)return;const s=canvasPos(e),w=screenToWorld(s.x,s.y);if(state.drag.pan){state.pan.x=state.drag.px+s.x-state.drag.x;state.pan.y=state.drag.py+s.y-state.drag.y;draw();return}const d=state.drag.part;d.x=state.drag.ox+(w.x-state.drag.x0);d.y=state.drag.oy+(w.y-state.drag.y0);draw()});
addEventListener('mouseup',()=>{if(state.drag?.part){const o=state.drag.part,s=snapPosition(o,o.x,o.y);o.x=s.x;o.y=s.y;recalc()}state.drag=null});canvas.oncontextmenu=e=>e.preventDefault();canvas.addEventListener('wheel',e=>{e.preventDefault();const old=state.zoom;state.zoom=Math.max(.45,Math.min(2.3,old*(e.deltaY<0?1.1:.9)));draw()},{passive:false});
addEventListener('keydown',e=>{if(e.key.toLowerCase()==='r'&&state.selected){const o=state.parts.find(x=>x.id===state.selected);o.rot=(o.rot+90)%360;draw();updateInspector()}if(e.key==='Delete'&&state.selected)deleteSelected();if(e.key===' '){if(!flight.classList.contains('hidden')){e.preventDefault();advanceStage()}}});
function draw(){const w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);ctx.fillStyle='#070b11';ctx.fillRect(0,0,w,h);if(state.grid){ctx.strokeStyle='#101821';ctx.lineWidth=1;const step=32*state.zoom;for(let x=(w/2+state.pan.x)%step;x<w;x+=step){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=(h*.82+state.pan.y)%step;y<h;y+=step){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}}const base=worldToScreen(0,0);ctx.strokeStyle='#243343';ctx.beginPath();ctx.moveTo(0,base.y);ctx.lineTo(w,base.y);ctx.stroke();for(const o of state.parts){const p=parts[o.type],s=worldToScreen(o.x,o.y);ctx.save();ctx.translate(s.x,s.y);ctx.rotate(o.rot*Math.PI/180);ctx.fillStyle=p.color;ctx.strokeStyle=o.id===state.selected?'#7edcff':'#344352';ctx.lineWidth=o.id===state.selected?2:1;ctx.beginPath();ctx.roundRect(-p.w*state.zoom/2,-p.h*state.zoom/2,p.w*state.zoom,p.h*state.zoom,5*state.zoom);ctx.fill();ctx.stroke();ctx.fillStyle='#dce9f5';ctx.font=`${Math.max(9,11*state.zoom)}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(p.name.split(' ')[0],0,0);ctx.restore();if(state.nodes){for(const side of ['top','bottom']){const n=node(o,side),ns=worldToScreen(n.x,n.y);ctx.beginPath();ctx.arc(ns.x,ns.y,4,0,Math.PI*2);ctx.fillStyle='#71d7ff';ctx.fill();}}if(o.id===state.selected){ctx.strokeStyle='#72d8ff55';ctx.setLineDash([4,4]);const x=s.x-p.w*state.zoom/2-6,y=s.y-p.h*state.zoom/2-6;ctx.strokeRect(x,y,p.w*state.zoom+12,p.h*state.zoom+12);ctx.setLineDash([])}}
function recalc(){let mass=0,fuel=0,thrust=0;for(const o of state.parts){const p=parts[o.type];mass+=p.mass;fuel+=p.fuel;thrust+=p.thrust}const dry=Math.max(.01,mass-fuel),tw=mass?thrust/(mass*9.80665):0;let dv=0,m=mass;const stages=[...new Set(state.parts.map(o=>o.stage))].sort((a,b)=>a-b);for(const st of stages){const f=state.parts.filter(o=>o.stage===st).reduce((a,o)=>a+parts[o.type].fuel,0);const e=state.parts.filter(o=>o.stage===st).reduce((a,o)=>a+parts[o.type].thrust,0);if(e&&f){const m0=m,m1=Math.max(m-f,.01);dv+=Math.max(0,300*Math.log(m0/m1));m=m1}}let sx=0,sy=0;if(state.parts.length){for(const o of state.parts){sx+=o.x*parts[o.type].mass;sy+=o.y*parts[o.type].mass}sx/=mass;sy/=mass}$('partsMetric').textContent=state.parts.length;$('massMetric').textContent=mass.toFixed(2)+' t';$('fuelMetric').textContent=fuel.toFixed(2)+' t';$('thrustMetric').textContent=Math.round(thrust)+' kN';$('twrMetric').textContent=tw.toFixed(2);$('dvMetric').textContent=Math.round(dv)+' m/s';$('comMetric').textContent=`${sx.toFixed(1)}, ${sy.toFixed(1)}`;state.stageCount=state.parts.length?Math.max(...state.parts.map(o=>o.stage))+1:0;$('stagesMetric').textContent=state.stageCount;$('stageLabel').textContent='STAGES: '+state.stageCount;renderStaging();updateInspector();draw()}
function renderStaging(){const box=$('staging');box.innerHTML='';for(let st=0;st<state.stageCount;st++){const arr=state.parts.filter(o=>o.stage===st);const d=document.createElement('div');d.className='stage-row';d.innerHTML=`<div class="stage-num">${st+1}</div><div class="stage-items">${arr.length?arr.map(o=>parts[o.type].name).join(', '):'EMPTY STAGE'}</div><button class="stage-fire" data-st="${st}">FIRE</button>`;d.querySelector('button').onclick=()=>startFlight(st);box.appendChild(d)}}
function updateInspector(){const o=state.parts.find(x=>x.id===state.selected);if(!o){$('selectedInfo').textContent='Nothing selected';return}const p=parts[o.type];$('selectedInfo').innerHTML=`<b>${p.name}</b><br>Mass ${p.mass.toFixed(2)} t · Fuel ${p.fuel.toFixed(2)} t · ${p.thrust?p.thrust+' kN thrust':'structural'}<br>Position ${o.x.toFixed(1)}, ${o.y.toFixed(1)} · Rotation ${o.rot}°<br>Stage <button id="stageCycle">${o.stage+1}</button>`;$('stageCycle').onclick=()=>{o.stage++;recalc()}}
function deleteSelected(){state.parts=state.parts.filter(x=>x.id!==state.selected);state.selected=null;recalc()}
$('rotateBtn').onclick=()=>{const o=state.parts.find(x=>x.id===state.selected);if(o){o.rot=(o.rot+90)%360;recalc()}};$('duplicateBtn').onclick=()=>{const o=state.parts.find(x=>x.id===state.selected);if(o){const n=addPart(o.type,o.x+parts[o.type].w+10,o.y,o.rot,o.stage);n.symmetry=o.symmetry;recalc()}};$('deleteBtn').onclick=deleteSelected;$('gridToggle').onchange=e=>{state.grid=e.target.checked;draw()};$('nodeToggle').onchange=e=>{state.nodes=e.target.checked;draw()};
$('newBtn').onclick=()=>{if(confirm('Clear current rocket?')){state.parts=[];state.selected=null;recalc()}};
$('saveBtn').onclick=()=>{localStorage.setItem('mraft-rocket-v1',JSON.stringify(state.parts));$('status').textContent=' SAVED';setTimeout(()=>recalc(),700)};
$('loadBtn').onclick=()=>{const x=localStorage.getItem('mraft-rocket-v1');if(!x){alert('No saved rocket found.');return}try{state.parts=JSON.parse(x);state.selected=null;recalc();$('status').textContent=' LOADED'}catch(e){alert('Save data is invalid.')}};
const flight=$('flight');let sim=null;
function buildFlight(st){return state.parts.map(o=>({...o,p:{...parts[o.type]}})).sort((a,b)=>a.y-b.y)}
function startFlight(initial=0){if(!state.parts.length){alert('Build a rocket first.');return}if(!state.parts.some(o=>parts[o.type].capsule)){alert('Add a command capsule before launch.');return}sim={parts:buildFlight(initial),stage:initial,time:0,alt:0,vel:0,x:0,ground:0,active:true,fuel:state.parts.reduce((a,o)=>a+parts[o.type].fuel,0),heading:Math.PI/2};flight.classList.remove('hidden');resizeFlight();requestAnimationFrame(flightLoop)}
function resizeFlight(){const r=flightCanvas.getBoundingClientRect(),d=devicePixelRatio||1;flightCanvas.width=r.width*d;flightCanvas.height=r.height*d;fctx.setTransform(d,0,0,d,0,0)}
function stageParts(s){return sim.parts.filter(o=>o.stage===s)}
function advanceStage(){if(!sim)return;const dec=stageParts(sim.stage).filter(o=>o.p.decoupler);if(dec.length){const cut=Math.min(...dec.map(o=>o.y));sim.parts=sim.parts.filter(o=>o.y>=cut);}
sim.stage++;if(sim.stage>20)sim.active=false}
$('stageNext').onclick=advanceStage;$('abortBtn').onclick=()=>{sim=null;flight.classList.add('hidden')};
function flightLoop(now){if(!sim)return;const dt=Math.min(.05,(now-(sim.last||now))/1000);sim.last=now;if(sim.active){sim.time+=dt;let mass=sim.parts.reduce((a,o)=>a+o.p.mass,0);let fuel=sim.parts.reduce((a,o)=>a+o.p.fuel,0);let engines=stageParts(sim.stage).filter(o=>o.p.thrust);let thrust=engines.reduce((a,o)=>a+o.p.thrust,0);if(fuel>0&&thrust>0){const burn=Math.min(fuel,dt*thrust/1000*.24);let left=burn;for(const o of sim.parts){if(left<=0)break;const take=Math.min(o.p.fuel,left);o.p.fuel-=take;left-=take}mass=Math.max(.1,mass-burn);const a=(thrust*1000/mass)-9.80665;sim.vel+=a*dt;sim.alt=Math.max(0,sim.alt+sim.vel*dt)}else sim.vel-=9.80665*dt;sim.vel=Math.max(-50,sim.vel);if(sim.alt<=0&&sim.time>1){sim.alt=0;if(sim.vel<0)sim.vel=0}}
drawFlight();if(sim.active)requestAnimationFrame(flightLoop)}
function drawFlight(){const w=flightCanvas.clientWidth,h=flightCanvas.clientHeight;fctx.fillStyle='#02050b';fctx.fillRect(0,0,w,h);const ground=h*.78;fctx.fillStyle='#111b26';fctx.fillRect(0,ground,w,h-ground);fctx.strokeStyle='#273b4e';fctx.beginPath();fctx.moveTo(0,ground);fctx.lineTo(w,ground);fctx.stroke();for(let i=0;i<35;i++){const x=(i*137)%w;const y=50+(i*71)%Math.max(80,ground-80);fctx.fillStyle='#b7d2e8';fctx.globalAlpha=.35;fctx.fillRect(x,y,1,1)}fctx.globalAlpha=1;const rocketX=w/2,rocketY=ground-40-Math.min(ground-100,sim.alt*.15);fctx.save();fctx.translate(rocketX,rocketY);fctx.fillStyle='#d6dee8';fctx.strokeStyle='#7f91a5';fctx.lineWidth=2;fctx.beginPath();fctx.roundRect(-18,-34,36,58,7);fctx.fill();fctx.stroke();fctx.fillStyle='#6bc8e8';fctx.beginPath();fctx.arc(0,-19,7,0,Math.PI*2);fctx.fill();fctx.fillStyle='#e8b45d';fctx.fillRect(-10,24,20,10);const burning=stageParts(sim.stage).some(o=>o.p.thrust&&o.p.fuel>0);if(burning){fctx.fillStyle='#ffcf75';fctx.beginPath();fctx.moveTo(-7,35);fctx.lineTo(0,35+25+Math.random()*15);fctx.lineTo(7,35);fctx.fill()}fctx.restore();$('flightReadout').textContent=`ALT ${Math.round(sim.alt)} m · VEL ${Math.round(sim.vel)} m/s · T+${sim.time.toFixed(1)} s · STAGE ${sim.stage+1}`}
renderParts();recalc();resize();
